services:
  api:
    build: ./api
    depends_on:
      - haproxy
      - db-replica
      - redis
    environment:
      - PORT=3000

      - WRITE_DB_HOST=haproxy
      - WRITE_DB_PORT=5432

      - READ_DB_HOST=db-replica
      - READ_DB_PORT=5432

      - DB_USER=app
      - DB_PASSWORD=app_pwd
      - DB_NAME=appdb

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL_SECONDS=60
    ports:
      - "3000:3000"

  db-primary:
    container_name: db-primary
    image: bitnamilegacy/postgresql:16.6.0-debian-12-r0
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pwd
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pwd
    ports:
      - "5432:5432"

  db-replica:
    container_name: db-replica
    image: bitnamilegacy/postgresql:16.6.0-debian-12-r0
    depends_on:
      - db-primary
    environment:
      - POSTGRESQL_USERNAME=app
      - POSTGRESQL_PASSWORD=app_pwd
      - POSTGRESQL_DATABASE=appdb
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=db-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl
      - POSTGRESQL_REPLICATION_PASSWORD=repl_pwd
    ports:
      - "5433:5432"

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

  haproxy:
    container_name: haproxy
    image: haproxy:2.9
    depends_on:
      - db-primary
      - db-replica
    ports:
      - "5439:5432"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro